In [350]:
import pandas as pd
import numpy as np
#base_1 = pd.read_csv("/content/IDG_1.csv")
#base_2 = pd.read_csv("/content/IDG_2.csv", encoding='latin-1')

In [351]:
#base_1.shape

In [352]:
#base_1.head(5)

In [353]:
#base_1

In [354]:
#base_2.shape

In [355]:
#base_2.tail(5)

In [356]:
!pip install openpyxl
import openpyxl
base3 = pd.read_excel("/content/IDH.xlsx")

Requirement already satisfied: openpyxl in /usr/local/lib/python3.10/dist-packages (3.1.2)
Requirement already satisfied: et-xmlfile in /usr/local/lib/python3.10/dist-packages (from openpyxl) (1.1.0)

In [357]:
base3.head(3)

,Índice de Desarollo Humano IDH 2017,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Logro educativo,NaN,NaN,NaN,NaN,NaN,Valores normalizados,NaN,NaN,NaN,NaN
1,UBIGEO,DEPARTAMENTO,NaN,NaN,NaN,Población total,Esperanza de vida al nacer,Población (18 años) con Educ. secundaria completa,Años de educación (Poblac. 25 y más),Ingreso familiar per cápita,NaN,Índice de Desarrollo Humano (IDH),NaN,Esperanza de vida al nacer,Población (18 años) con Educ. secundaria completa,Años de educación (Poblac. 25 y más),Logro educativo,Ingreso familiar per cápita
2,NaN,NaN,Provincia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [358]:
departamentos = pd.read_excel("/content/IDH.xlsx", sheet_name="Departamental")

In [359]:
departamentos.head(10)

,"Índice de Desarrollo Humano departamental, 2017",Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,UBIGEO,DEPARTAMENTO,NaN,NaN,NaN,Población,NaN,Índice de Desarrollo Humano,NaN,Esperanza de vida al nacer,NaN,Con Educación secundaria completa (Poblac. 18 ...,NaN,Años de educación (Poblac. 25 y más),NaN,Ingreso familiar per cápita,NaN,NaN,NaN,NaN
2,NaN,NaN,Provincia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,Distrito,NaN,NaN,habitantes,ranking,IDH,ranking,años,ranking,%,ranking,años,ranking,N.S. mes,ranking,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,000000,PERÚ,NaN,NaN,NaN,29381884,NaN,0.572345,NaN,75.52714,NaN,67.108865,NaN,8.78599,NaN,990.116633,NaN,NaN,NaN,1.0
7,010000,AMAZONAS,NaN,NaN,NaN,379384,19,0.417452,21,73.306564,15,46.859333,24,6.050521,23,629.7113,18,NaN,NaN,2.0
8,020000,ANCASH,NaN,NaN,NaN,1083519,10,0.488391,12,75.743889,10,61.110602,16,7.633381,15,712.6623,13,NaN,NaN,3.0
9,030000,APURÍMAC,NaN,NaN,NaN,405759,18,0.416742,22,72.634854,19,65.547677,13,6.610242,21,511.8983,24,NaN,NaN,4.0

In [360]:
departamentos.shape

(35, 20)

In [361]:
departamentos.tail(10)

,"Índice de Desarrollo Humano departamental, 2017",Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19
25,190000,PASCO,NaN,NaN,NaN,254065,22,0.460667,17,72.040411,20,68.253589,8,8.141167,11,591.7423,20,NaN,NaN,20.0
26,200000,PIURA,NaN,NaN,NaN,1856809,2,0.479728,13,73.696331,14,61.930024,15,7.577943,16,702.9804,16,NaN,NaN,21.0
27,210000,PUNO,NaN,NaN,NaN,1172697,9,0.427841,20,68.475641,24,72.150998,7,7.447559,18,532.3485,22,NaN,NaN,22.0
28,220000,SAN MARTÍN,NaN,NaN,NaN,813381,14,0.467982,16,73.718529,13,52.462043,21,6.644659,20,770.4451,11,NaN,NaN,23.0
29,230000,TACNA,NaN,NaN,NaN,329332,21,0.606991,6,77.53434,7,74.913182,3,9.810744,6,1003.4997,5,NaN,NaN,24.0
30,240000,TUMBES,NaN,NaN,NaN,224863,23,0.559666,8,79.057924,5,66.70287,10,8.666748,8,879.4833,9,NaN,NaN,25.0
31,250000,UCAYALI,NaN,NaN,NaN,496459,17,0.470985,14,72.861223,18,51.943499,22,8.052112,12,710.1024,15,NaN,NaN,26.0
32,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,Fuente: INEI. Censo de Población y Vivienda 20...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,Elaboración: PNUD / Unidad del Informe sobre D...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# Inicio de transformación de la base de datos “cruda”⭐

In [362]:
#Inicio de la limpieza
depas = departamentos.drop([0,4,5,32,33,34], axis=0)
depas

,"Índice de Desarrollo Humano departamental, 2017",Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19
1,UBIGEO,DEPARTAMENTO,NaN,NaN,NaN,Población,NaN,Índice de Desarrollo Humano,NaN,Esperanza de vida al nacer,NaN,Con Educación secundaria completa (Poblac. 18 ...,NaN,Años de educación (Poblac. 25 y más),NaN,Ingreso familiar per cápita,NaN,NaN,NaN,NaN
2,NaN,NaN,Provincia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,Distrito,NaN,NaN,habitantes,ranking,IDH,ranking,años,ranking,%,ranking,años,ranking,N.S. mes,ranking,NaN,NaN,NaN
6,000000,PERÚ,NaN,NaN,NaN,29381884,NaN,0.572345,NaN,75.52714,NaN,67.108865,NaN,8.78599,NaN,990.116633,NaN,NaN,NaN,1.0
7,010000,AMAZONAS,NaN,NaN,NaN,379384,19,0.417452,21,73.306564,15,46.859333,24,6.050521,23,629.7113,18,NaN,NaN,2.0
8,020000,ANCASH,NaN,NaN,NaN,1083519,10,0.488391,12,75.743889,10,61.110602,16,7.633381,15,712.6623,13,NaN,NaN,3.0
9,030000,APURÍMAC,NaN,NaN,NaN,405759,18,0.416742,22,72.634854,19,65.547677,13,6.610242,21,511.8983,24,NaN,NaN,4.0
10,040000,AREQUIPA,NaN,NaN,NaN,1382730,4,0.634479,4,78.203421,6,77.80172,1,10.097563,2,1088.0636,4,NaN,NaN,5.0
11,050000,AYACUCHO,NaN,NaN,NaN,616176,16,0.409602,23,71.078435,22,59.357975,18,6.905559,19,512.4642,23,NaN,NaN,6.0
12,060000,CAJAMARCA,NaN,NaN,NaN,1341012,5,0.40106,24,74.746021,11,51.376462,23,5.607542,25,551.7471,21,NaN,NaN,7.0
13,070100,Provincia Constitucional del CALLAO,NaN,NaN,NaN,994494,11,0.666302,2,82.515232,1,73.497518,6,10.062423,3,1198.1964,2,NaN,NaN,8.0
14,080000,CUSCO,NaN,NaN,NaN,1205527,7,0.470121,15,70.740178,23,66.690447,11,7.798155,14,667.9998,17,NaN,NaN,9.0
15,090000,HUANCAVELICA,NaN,NaN,NaN,347639,20,0.335663,25,64.034012,25,56.184207,19,5.735151,24,398.1561,25,NaN,NaN,10.0
16,100000,HUÁNUCO,NaN,NaN,NaN,721047,15,0.428468,19,73.110342,17,53.614801,20,6.572781,22,604.6419,19,NaN,NaN,11.0
17,110000,ICA,NaN,NaN,NaN,850765,13,0.612103,5,81.663418,2,73.527836,5,9.905355,5,958.9974,7,NaN,NaN,12.0
18,120000,JUNÍN,NaN,NaN,NaN,1246038,6,0.495384,11,73.181276,16,65.8842,12,8.381481,10,710.3179,14,NaN,NaN,13.0
19,130000,LA LIBERTAD,NaN,NaN,NaN,1778080,3,0.538779,10,77.214338,9,60.848472,17,8.033712,13,892.1488,8,NaN,NaN,14.0
20,140000,LAMBAYEQUE,NaN,NaN,NaN,1197260,8,0.53949,9,77.288576,8,67.090434,9,8.445149,9,827.6347,10,NaN,NaN,15.0
21,150000,LIMA,NaN,NaN,NaN,9485405,1,0.715651,1,81.153518,3,75.707688,2,10.35686,1,1464.2608,1,NaN,NaN,16.0
22,160000,LORETO,NaN,NaN,NaN,883510,12,0.454914,18,71.419194,21,45.044803,25,7.560003,17,736.7302,12,NaN,NaN,17.0
23,170000,MADRE DE DIOS,NaN,NaN,NaN,141070,25,0.56188,7,73.718619,12,63.758325,14,8.726031,7,1000.6915,6,NaN,NaN,18.0
24,180000,MOQUEGUA,NaN,NaN,NaN,174863,24,0.638726,3,79.800886,4,74.491285,4,9.921653,4,1112.4407,3,NaN,NaN,19.0
25,190000,PASCO,NaN,NaN,NaN,254065,22,0.460667,17,72.040411,20,68.253589,8,8.141167,11,591.7423,20,NaN,NaN,20.0
26,200000,PIURA,NaN,NaN,NaN,1856809,2,0.479728,13,73.696331,14,61.930024,15,7.577943,16,702.9804,16,NaN,NaN,21.0
27,210000,PUNO,NaN,NaN,NaN,1172697,9,0.427841,20,68.475641,24,72.150998,7,7.447559,18,532.3485,22,NaN,NaN,22.0
28,220000,SAN MARTÍN,NaN,NaN,NaN,813381,14,0.467982,16,73.718529,13,52.462043,21,6.644659,20,770.4451,11,NaN,NaN,23.0
29,230000,TACNA,NaN,NaN,NaN,329332,21,0.606991,6,77.53434,7,74.913182,3,9.810744,6,1003.4997,5,NaN,NaN,24.0
30,240000,TUMBES,NaN,NaN,NaN,224863,23,0.559666,8,79.057924,5,66.70287,10,8.666748,8,879.4833,9,NaN,NaN,25.0
31,250000,UCAYALI,NaN,NaN,NaN,496459,17,0.470985,14,72.861223,18,51.943499,22,8.052112,12,710.1024,15,NaN,NaN,26.0

In [363]:
depas.columns

Index(['Índice de Desarrollo Humano departamental, 2017', 'Unnamed: 1',
       'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5', 'Unnamed: 6',
       'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11',
       'Unnamed: 12', 'Unnamed: 13', 'Unnamed: 14', 'Unnamed: 15',
       'Unnamed: 16', 'Unnamed: 17', 'Unnamed: 18', 'Unnamed: 19'],
      dtype='object')

## Dataframe sucia ⭐

In [364]:
depas = depas.drop(depas.columns[[2, 3, 4, 17, 18]],axis=1)
depas

,"Índice de Desarrollo Humano departamental, 2017",Unnamed: 1,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 19
1,UBIGEO,DEPARTAMENTO,Población,NaN,Índice de Desarrollo Humano,NaN,Esperanza de vida al nacer,NaN,Con Educación secundaria completa (Poblac. 18 ...,NaN,Años de educación (Poblac. 25 y más),NaN,Ingreso familiar per cápita,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,habitantes,ranking,IDH,ranking,años,ranking,%,ranking,años,ranking,N.S. mes,ranking,NaN
6,000000,PERÚ,29381884,NaN,0.572345,NaN,75.52714,NaN,67.108865,NaN,8.78599,NaN,990.116633,NaN,1.0
7,010000,AMAZONAS,379384,19,0.417452,21,73.306564,15,46.859333,24,6.050521,23,629.7113,18,2.0
8,020000,ANCASH,1083519,10,0.488391,12,75.743889,10,61.110602,16,7.633381,15,712.6623,13,3.0
9,030000,APURÍMAC,405759,18,0.416742,22,72.634854,19,65.547677,13,6.610242,21,511.8983,24,4.0
10,040000,AREQUIPA,1382730,4,0.634479,4,78.203421,6,77.80172,1,10.097563,2,1088.0636,4,5.0
11,050000,AYACUCHO,616176,16,0.409602,23,71.078435,22,59.357975,18,6.905559,19,512.4642,23,6.0
12,060000,CAJAMARCA,1341012,5,0.40106,24,74.746021,11,51.376462,23,5.607542,25,551.7471,21,7.0
13,070100,Provincia Constitucional del CALLAO,994494,11,0.666302,2,82.515232,1,73.497518,6,10.062423,3,1198.1964,2,8.0
14,080000,CUSCO,1205527,7,0.470121,15,70.740178,23,66.690447,11,7.798155,14,667.9998,17,9.0
15,090000,HUANCAVELICA,347639,20,0.335663,25,64.034012,25,56.184207,19,5.735151,24,398.1561,25,10.0
16,100000,HUÁNUCO,721047,15,0.428468,19,73.110342,17,53.614801,20,6.572781,22,604.6419,19,11.0
17,110000,ICA,850765,13,0.612103,5,81.663418,2,73.527836,5,9.905355,5,958.9974,7,12.0
18,120000,JUNÍN,1246038,6,0.495384,11,73.181276,16,65.8842,12,8.381481,10,710.3179,14,13.0
19,130000,LA LIBERTAD,1778080,3,0.538779,10,77.214338,9,60.848472,17,8.033712,13,892.1488,8,14.0
20,140000,LAMBAYEQUE,1197260,8,0.53949,9,77.288576,8,67.090434,9,8.445149,9,827.6347,10,15.0
21,150000,LIMA,9485405,1,0.715651,1,81.153518,3,75.707688,2,10.35686,1,1464.2608,1,16.0
22,160000,LORETO,883510,12,0.454914,18,71.419194,21,45.044803,25,7.560003,17,736.7302,12,17.0
23,170000,MADRE DE DIOS,141070,25,0.56188,7,73.718619,12,63.758325,14,8.726031,7,1000.6915,6,18.0
24,180000,MOQUEGUA,174863,24,0.638726,3,79.800886,4,74.491285,4,9.921653,4,1112.4407,3,19.0
25,190000,PASCO,254065,22,0.460667,17,72.040411,20,68.253589,8,8.141167,11,591.7423,20,20.0
26,200000,PIURA,1856809,2,0.479728,13,73.696331,14,61.930024,15,7.577943,16,702.9804,16,21.0
27,210000,PUNO,1172697,9,0.427841,20,68.475641,24,72.150998,7,7.447559,18,532.3485,22,22.0
28,220000,SAN MARTÍN,813381,14,0.467982,16,73.718529,13,52.462043,21,6.644659,20,770.4451,11,23.0
29,230000,TACNA,329332,21,0.606991,6,77.53434,7,74.913182,3,9.810744,6,1003.4997,5,24.0
30,240000,TUMBES,224863,23,0.559666,8,79.057924,5,66.70287,10,8.666748,8,879.4833,9,25.0
31,250000,UCAYALI,496459,17,0.470985,14,72.861223,18,51.943499,22,8.052112,12,710.1024,15,26.0

In [365]:
depas.shape

(29, 15)

In [366]:
depas.head(2)

,"Índice de Desarrollo Humano departamental, 2017",Unnamed: 1,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 19
1,UBIGEO,DEPARTAMENTO,Población,NaN,Índice de Desarrollo Humano,NaN,Esperanza de vida al nacer,NaN,Con Educación secundaria completa (Poblac. 18 ...,NaN,Años de educación (Poblac. 25 y más),NaN,Ingreso familiar per cápita,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [367]:
fila1 = fila_seleccionada_loc = depas.loc[1]
fila1

Índice de Desarrollo Humano departamental, 2017                                               UBIGEO
Unnamed: 1                                                                              DEPARTAMENTO
Unnamed: 5                                                                                 Población
Unnamed: 6                                                                                       NaN
Unnamed: 7                                                               Índice de Desarrollo Humano
Unnamed: 8                                                                                       NaN
Unnamed: 9                                                                Esperanza de vida al nacer
Unnamed: 10                                                                                      NaN
Unnamed: 11                                        Con Educación secundaria completa (Poblac. 18 ...
Unnamed: 12                                                                                      NaN
Unnamed: 13                                                     Años de educación (Poblac. 25 y más)
Unnamed: 14                                                                                      NaN
Unnamed: 15                                                              Ingreso familiar per cápita
Unnamed: 16                                                                                      NaN
Unnamed: 19                                                                                      NaN
Name: 1, dtype: object

In [368]:
nombres_columna = {'Índice de Desarrollo Humano departamental, 2017':'UBIGEO',
                   'Unnamed: 1':'DEPARTAMENTO',
                   'Unnamed: 5':'Población',
                   'Unnamed: 6':'Ranking población',
                   'Unnamed: 7':'Índice de Desarrollo Humano',
                   'Unnamed: 8':'Ranking IDH',
                   'Unnamed: 9':'Esperanza de vida al nacer (años)',
                   'Unnamed: 10':'Ranking esperanza de vida al nacer',
                   'Unnamed: 11':'Con Educación secundaria completa % (Poblac. 18)',
                   'Unnamed: 12':'Ranking Educación secundaria completa',
                   'Unnamed: 13':'Años de educación (Poblac. 25 y más)',
                   'Unnamed: 14':'Ranking años de educación',
                   'Unnamed: 15':'Ingreso familiar per cápita',
                   'Unnamed: 16':'Ranking ingreso familiar',
                   'Unnamed: 19':'NN'}

In [369]:
depas.rename(columns=nombres_columna, inplace=True)
depas.head(5)

,UBIGEO,DEPARTAMENTO,Población,Ranking población,Índice de Desarrollo Humano,Ranking IDH,Esperanza de vida al nacer (años),Ranking esperanza de vida al nacer,Con Educación secundaria completa % (Poblac. 18),Ranking Educación secundaria completa,Años de educación (Poblac. 25 y más),Ranking años de educación,Ingreso familiar per cápita,Ranking ingreso familiar,NN
1,UBIGEO,DEPARTAMENTO,Población,NaN,Índice de Desarrollo Humano,NaN,Esperanza de vida al nacer,NaN,Con Educación secundaria completa (Poblac. 18 ...,NaN,Años de educación (Poblac. 25 y más),NaN,Ingreso familiar per cápita,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,habitantes,ranking,IDH,ranking,años,ranking,%,ranking,años,ranking,N.S. mes,ranking,NaN
6,000000,PERÚ,29381884,NaN,0.572345,NaN,75.52714,NaN,67.108865,NaN,8.78599,NaN,990.116633,NaN,1.0
7,010000,AMAZONAS,379384,19,0.417452,21,73.306564,15,46.859333,24,6.050521,23,629.7113,18,2.0

In [370]:
depas2 = depas.drop([1,2], axis=0)
depas2

,UBIGEO,DEPARTAMENTO,Población,Ranking población,Índice de Desarrollo Humano,Ranking IDH,Esperanza de vida al nacer (años),Ranking esperanza de vida al nacer,Con Educación secundaria completa % (Poblac. 18),Ranking Educación secundaria completa,Años de educación (Poblac. 25 y más),Ranking años de educación,Ingreso familiar per cápita,Ranking ingreso familiar,NN
3,NaN,NaN,habitantes,ranking,IDH,ranking,años,ranking,%,ranking,años,ranking,N.S. mes,ranking,NaN
6,000000,PERÚ,29381884,NaN,0.572345,NaN,75.52714,NaN,67.108865,NaN,8.78599,NaN,990.116633,NaN,1.0
7,010000,AMAZONAS,379384,19,0.417452,21,73.306564,15,46.859333,24,6.050521,23,629.7113,18,2.0
8,020000,ANCASH,1083519,10,0.488391,12,75.743889,10,61.110602,16,7.633381,15,712.6623,13,3.0
9,030000,APURÍMAC,405759,18,0.416742,22,72.634854,19,65.547677,13,6.610242,21,511.8983,24,4.0
10,040000,AREQUIPA,1382730,4,0.634479,4,78.203421,6,77.80172,1,10.097563,2,1088.0636,4,5.0
11,050000,AYACUCHO,616176,16,0.409602,23,71.078435,22,59.357975,18,6.905559,19,512.4642,23,6.0
12,060000,CAJAMARCA,1341012,5,0.40106,24,74.746021,11,51.376462,23,5.607542,25,551.7471,21,7.0
13,070100,Provincia Constitucional del CALLAO,994494,11,0.666302,2,82.515232,1,73.497518,6,10.062423,3,1198.1964,2,8.0
14,080000,CUSCO,1205527,7,0.470121,15,70.740178,23,66.690447,11,7.798155,14,667.9998,17,9.0
15,090000,HUANCAVELICA,347639,20,0.335663,25,64.034012,25,56.184207,19,5.735151,24,398.1561,25,10.0
16,100000,HUÁNUCO,721047,15,0.428468,19,73.110342,17,53.614801,20,6.572781,22,604.6419,19,11.0
17,110000,ICA,850765,13,0.612103,5,81.663418,2,73.527836,5,9.905355,5,958.9974,7,12.0
18,120000,JUNÍN,1246038,6,0.495384,11,73.181276,16,65.8842,12,8.381481,10,710.3179,14,13.0
19,130000,LA LIBERTAD,1778080,3,0.538779,10,77.214338,9,60.848472,17,8.033712,13,892.1488,8,14.0
20,140000,LAMBAYEQUE,1197260,8,0.53949,9,77.288576,8,67.090434,9,8.445149,9,827.6347,10,15.0
21,150000,LIMA,9485405,1,0.715651,1,81.153518,3,75.707688,2,10.35686,1,1464.2608,1,16.0
22,160000,LORETO,883510,12,0.454914,18,71.419194,21,45.044803,25,7.560003,17,736.7302,12,17.0
23,170000,MADRE DE DIOS,141070,25,0.56188,7,73.718619,12,63.758325,14,8.726031,7,1000.6915,6,18.0
24,180000,MOQUEGUA,174863,24,0.638726,3,79.800886,4,74.491285,4,9.921653,4,1112.4407,3,19.0
25,190000,PASCO,254065,22,0.460667,17,72.040411,20,68.253589,8,8.141167,11,591.7423,20,20.0
26,200000,PIURA,1856809,2,0.479728,13,73.696331,14,61.930024,15,7.577943,16,702.9804,16,21.0
27,210000,PUNO,1172697,9,0.427841,20,68.475641,24,72.150998,7,7.447559,18,532.3485,22,22.0
28,220000,SAN MARTÍN,813381,14,0.467982,16,73.718529,13,52.462043,21,6.644659,20,770.4451,11,23.0
29,230000,TACNA,329332,21,0.606991,6,77.53434,7,74.913182,3,9.810744,6,1003.4997,5,24.0
30,240000,TUMBES,224863,23,0.559666,8,79.057924,5,66.70287,10,8.666748,8,879.4833,9,25.0
31,250000,UCAYALI,496459,17,0.470985,14,72.861223,18,51.943499,22,8.052112,12,710.1024,15,26.0

In [371]:
depas2 = depas2.drop([3], axis=0)
depas2.head(2)

,UBIGEO,DEPARTAMENTO,Población,Ranking población,Índice de Desarrollo Humano,Ranking IDH,Esperanza de vida al nacer (años),Ranking esperanza de vida al nacer,Con Educación secundaria completa % (Poblac. 18),Ranking Educación secundaria completa,Años de educación (Poblac. 25 y más),Ranking años de educación,Ingreso familiar per cápita,Ranking ingreso familiar,NN
6,000000,PERÚ,29381884,NaN,0.572345,NaN,75.52714,NaN,67.108865,NaN,8.78599,NaN,990.116633,NaN,1.0
7,010000,AMAZONAS,379384,19,0.417452,21,73.306564,15,46.859333,24,6.050521,23,629.7113,18,2.0

In [372]:
depas2.columns

Index(['UBIGEO', 'DEPARTAMENTO', 'Población', 'Ranking población',
       'Índice de Desarrollo Humano', 'Ranking IDH',
       'Esperanza de vida al nacer (años)',
       'Ranking esperanza de vida al nacer',
       'Con Educación secundaria completa % (Poblac. 18)',
       'Ranking Educación secundaria completa',
       'Años de educación (Poblac. 25 y más)', 'Ranking años de educación',
       'Ingreso familiar per cápita', 'Ranking ingreso familiar', 'NN'],
      dtype='object')

In [373]:
depas2 = depas2.drop(depas2.columns[[14]],axis=1)
depas2

,UBIGEO,DEPARTAMENTO,Población,Ranking población,Índice de Desarrollo Humano,Ranking IDH,Esperanza de vida al nacer (años),Ranking esperanza de vida al nacer,Con Educación secundaria completa % (Poblac. 18),Ranking Educación secundaria completa,Años de educación (Poblac. 25 y más),Ranking años de educación,Ingreso familiar per cápita,Ranking ingreso familiar
6,000000,PERÚ,29381884,NaN,0.572345,NaN,75.52714,NaN,67.108865,NaN,8.78599,NaN,990.116633,NaN
7,010000,AMAZONAS,379384,19,0.417452,21,73.306564,15,46.859333,24,6.050521,23,629.7113,18
8,020000,ANCASH,1083519,10,0.488391,12,75.743889,10,61.110602,16,7.633381,15,712.6623,13
9,030000,APURÍMAC,405759,18,0.416742,22,72.634854,19,65.547677,13,6.610242,21,511.8983,24
10,040000,AREQUIPA,1382730,4,0.634479,4,78.203421,6,77.80172,1,10.097563,2,1088.0636,4
11,050000,AYACUCHO,616176,16,0.409602,23,71.078435,22,59.357975,18,6.905559,19,512.4642,23
12,060000,CAJAMARCA,1341012,5,0.40106,24,74.746021,11,51.376462,23,5.607542,25,551.7471,21
13,070100,Provincia Constitucional del CALLAO,994494,11,0.666302,2,82.515232,1,73.497518,6,10.062423,3,1198.1964,2
14,080000,CUSCO,1205527,7,0.470121,15,70.740178,23,66.690447,11,7.798155,14,667.9998,17
15,090000,HUANCAVELICA,347639,20,0.335663,25,64.034012,25,56.184207,19,5.735151,24,398.1561,25
16,100000,HUÁNUCO,721047,15,0.428468,19,73.110342,17,53.614801,20,6.572781,22,604.6419,19
17,110000,ICA,850765,13,0.612103,5,81.663418,2,73.527836,5,9.905355,5,958.9974,7
18,120000,JUNÍN,1246038,6,0.495384,11,73.181276,16,65.8842,12,8.381481,10,710.3179,14
19,130000,LA LIBERTAD,1778080,3,0.538779,10,77.214338,9,60.848472,17,8.033712,13,892.1488,8
20,140000,LAMBAYEQUE,1197260,8,0.53949,9,77.288576,8,67.090434,9,8.445149,9,827.6347,10
21,150000,LIMA,9485405,1,0.715651,1,81.153518,3,75.707688,2,10.35686,1,1464.2608,1
22,160000,LORETO,883510,12,0.454914,18,71.419194,21,45.044803,25,7.560003,17,736.7302,12
23,170000,MADRE DE DIOS,141070,25,0.56188,7,73.718619,12,63.758325,14,8.726031,7,1000.6915,6
24,180000,MOQUEGUA,174863,24,0.638726,3,79.800886,4,74.491285,4,9.921653,4,1112.4407,3
25,190000,PASCO,254065,22,0.460667,17,72.040411,20,68.253589,8,8.141167,11,591.7423,20
26,200000,PIURA,1856809,2,0.479728,13,73.696331,14,61.930024,15,7.577943,16,702.9804,16
27,210000,PUNO,1172697,9,0.427841,20,68.475641,24,72.150998,7,7.447559,18,532.3485,22
28,220000,SAN MARTÍN,813381,14,0.467982,16,73.718529,13,52.462043,21,6.644659,20,770.4451,11
29,230000,TACNA,329332,21,0.606991,6,77.53434,7,74.913182,3,9.810744,6,1003.4997,5
30,240000,TUMBES,224863,23,0.559666,8,79.057924,5,66.70287,10,8.666748,8,879.4833,9
31,250000,UCAYALI,496459,17,0.470985,14,72.861223,18,51.943499,22,8.052112,12,710.1024,15

In [374]:
depas2 = depas2.drop([6],axis=0)
depas2.head(2)

,UBIGEO,DEPARTAMENTO,Población,Ranking población,Índice de Desarrollo Humano,Ranking IDH,Esperanza de vida al nacer (años),Ranking esperanza de vida al nacer,Con Educación secundaria completa % (Poblac. 18),Ranking Educación secundaria completa,Años de educación (Poblac. 25 y más),Ranking años de educación,Ingreso familiar per cápita,Ranking ingreso familiar
7,010000,AMAZONAS,379384,19,0.417452,21,73.306564,15,46.859333,24,6.050521,23,629.7113,18
8,020000,ANCASH,1083519,10,0.488391,12,75.743889,10,61.110602,16,7.633381,15,712.6623,13

# Diccionario ⭐

In [375]:
#Almacenamos en una tabla la información general de Perú
info_peru = {
    'DEPARTAMENTO': ['PERÚ'],
    'Población': [29381884],
    'Índice de Desarrollo Humano': [0.5723445758691232],
    'Esperanza de vida al nacer (años)': [75.52713991212403],
    'Con Educación secundaria completa % (Poblac. 18)': [67.10886488582479],
    'Años de educación (Poblac. 25 y más)': [8.785990320005567],
    'Ingreso familiar per cápita': [990.1166331420851],
}

IDH_PERU = pd.DataFrame(info_peru)

# Imprimir el DataFrame
print("Índice de Desarrollo Humano de Perú\n", "\n", IDH_PERU)

Índice de Desarrollo Humano de Perú

   DEPARTAMENTO  Población  Índice de Desarrollo Humano  \
0         PERÚ   29381884                     0.572345

   Esperanza de vida al nacer (años)  \
0                           75.52714

   Con Educación secundaria completa % (Poblac. 18)  \
0                                         67.108865

   Años de educación (Poblac. 25 y más)  Ingreso familiar per cápita
0                               8.78599                   990.116633

# **Dataframe limpia** ⭐

In [376]:
IDH_depatamentos.dtypes

UBIGEO                                              float64
DEPARTAMENTO                                         object
Población                                           float64
Ranking población                                   float64
Índice de Desarrollo Humano                         float64
Ranking IDH                                         float64
Esperanza de vida al nacer (años)                   float64
Ranking esperanza de vida al nacer                  float64
Con Educación secundaria completa % (Poblac. 18)    float64
Ranking Educación secundaria completa               float64
Años de educación (Poblac. 25 y más)                float64
Ranking años de educación                           float64
Ingreso familiar per cápita                         float64
Ranking ingreso familiar                            float64
dtype: object

In [377]:
IDH_depatamentos.columns

Index(['UBIGEO', 'DEPARTAMENTO', 'Población', 'Ranking población',
       'Índice de Desarrollo Humano', 'Ranking IDH',
       'Esperanza de vida al nacer (años)',
       'Ranking esperanza de vida al nacer',
       'Con Educación secundaria completa % (Poblac. 18)',
       'Ranking Educación secundaria completa',
       'Años de educación (Poblac. 25 y más)', 'Ranking años de educación',
       'Ingreso familiar per cápita', 'Ranking ingreso familiar'],
      dtype='object')

In [378]:
a_float = ['UBIGEO', 'Población', 'Ranking población',
       'Índice de Desarrollo Humano', 'Ranking IDH',
       'Esperanza de vida al nacer (años)',
       'Ranking esperanza de vida al nacer',
       'Con Educación secundaria completa % (Poblac. 18)',
       'Ranking Educación secundaria completa',
       'Años de educación (Poblac. 25 y más)', 'Ranking años de educación',
       'Ingreso familiar per cápita', 'Ranking ingreso familiar']
IDH_depatamentos[a_float] = IDH_depatamentos[a_float].astype(float)

In [379]:
IDH_depatamentos = depas2.reset_index(drop=True)
IDH_depatamentos

,UBIGEO,DEPARTAMENTO,Población,Ranking población,Índice de Desarrollo Humano,Ranking IDH,Esperanza de vida al nacer (años),Ranking esperanza de vida al nacer,Con Educación secundaria completa % (Poblac. 18),Ranking Educación secundaria completa,Años de educación (Poblac. 25 y más),Ranking años de educación,Ingreso familiar per cápita,Ranking ingreso familiar
0,010000,AMAZONAS,379384,19,0.417452,21,73.306564,15,46.859333,24,6.050521,23,629.7113,18
1,020000,ANCASH,1083519,10,0.488391,12,75.743889,10,61.110602,16,7.633381,15,712.6623,13
2,030000,APURÍMAC,405759,18,0.416742,22,72.634854,19,65.547677,13,6.610242,21,511.8983,24
3,040000,AREQUIPA,1382730,4,0.634479,4,78.203421,6,77.80172,1,10.097563,2,1088.0636,4
4,050000,AYACUCHO,616176,16,0.409602,23,71.078435,22,59.357975,18,6.905559,19,512.4642,23
5,060000,CAJAMARCA,1341012,5,0.40106,24,74.746021,11,51.376462,23,5.607542,25,551.7471,21
6,070100,Provincia Constitucional del CALLAO,994494,11,0.666302,2,82.515232,1,73.497518,6,10.062423,3,1198.1964,2
7,080000,CUSCO,1205527,7,0.470121,15,70.740178,23,66.690447,11,7.798155,14,667.9998,17
8,090000,HUANCAVELICA,347639,20,0.335663,25,64.034012,25,56.184207,19,5.735151,24,398.1561,25
9,100000,HUÁNUCO,721047,15,0.428468,19,73.110342,17,53.614801,20,6.572781,22,604.6419,19
10,110000,ICA,850765,13,0.612103,5,81.663418,2,73.527836,5,9.905355,5,958.9974,7
11,120000,JUNÍN,1246038,6,0.495384,11,73.181276,16,65.8842,12,8.381481,10,710.3179,14
12,130000,LA LIBERTAD,1778080,3,0.538779,10,77.214338,9,60.848472,17,8.033712,13,892.1488,8
13,140000,LAMBAYEQUE,1197260,8,0.53949,9,77.288576,8,67.090434,9,8.445149,9,827.6347,10
14,150000,LIMA,9485405,1,0.715651,1,81.153518,3,75.707688,2,10.35686,1,1464.2608,1
15,160000,LORETO,883510,12,0.454914,18,71.419194,21,45.044803,25,7.560003,17,736.7302,12
16,170000,MADRE DE DIOS,141070,25,0.56188,7,73.718619,12,63.758325,14,8.726031,7,1000.6915,6
17,180000,MOQUEGUA,174863,24,0.638726,3,79.800886,4,74.491285,4,9.921653,4,1112.4407,3
18,190000,PASCO,254065,22,0.460667,17,72.040411,20,68.253589,8,8.141167,11,591.7423,20
19,200000,PIURA,1856809,2,0.479728,13,73.696331,14,61.930024,15,7.577943,16,702.9804,16
20,210000,PUNO,1172697,9,0.427841,20,68.475641,24,72.150998,7,7.447559,18,532.3485,22
21,220000,SAN MARTÍN,813381,14,0.467982,16,73.718529,13,52.462043,21,6.644659,20,770.4451,11
22,230000,TACNA,329332,21,0.606991,6,77.53434,7,74.913182,3,9.810744,6,1003.4997,5
23,240000,TUMBES,224863,23,0.559666,8,79.057924,5,66.70287,10,8.666748,8,879.4833,9
24,250000,UCAYALI,496459,17,0.470985,14,72.861223,18,51.943499,22,8.052112,12,710.1024,15

In [380]:
IDH_depatamentos.dtypes

UBIGEO                                              object
DEPARTAMENTO                                        object
Población                                           object
Ranking población                                   object
Índice de Desarrollo Humano                         object
Ranking IDH                                         object
Esperanza de vida al nacer (años)                   object
Ranking esperanza de vida al nacer                  object
Con Educación secundaria completa % (Poblac. 18)    object
Ranking Educación secundaria completa               object
Años de educación (Poblac. 25 y más)                object
Ranking años de educación                           object
Ingreso familiar per cápita                         object
Ranking ingreso familiar                            object
dtype: object

In [381]:
IDH_depatamentos=pd.DataFrame(IDH_depatamentos)

# **Listas ⭐**

In [382]:
#En Python, una lista es una estructura de datos que se utiliza para almacenar
#una colección ordenada de elementos. Puedes almacenar cualquier tipo de objeto
#en una lista, como números, cadenas, booleanos, otras listas, etc.

#Lista con ranking (población-departamento-ranking)
#Ranking IDH de departamenso
IDH_depatamentos.columns

Index(['UBIGEO', 'DEPARTAMENTO', 'Población', 'Ranking población',
       'Índice de Desarrollo Humano', 'Ranking IDH',
       'Esperanza de vida al nacer (años)',
       'Ranking esperanza de vida al nacer',
       'Con Educación secundaria completa % (Poblac. 18)',
       'Ranking Educación secundaria completa',
       'Años de educación (Poblac. 25 y más)', 'Ranking años de educación',
       'Ingreso familiar per cápita', 'Ranking ingreso familiar'],
      dtype='object')

In [383]:
ranking_poblacion = IDH_depatamentos[['DEPARTAMENTO', 'Población', 'Ranking población']]
ranking_poblacion

                           DEPARTAMENTO Población Ranking población
0                              AMAZONAS    379384                19
1                                ANCASH   1083519                10
2                              APURÍMAC    405759                18
3                              AREQUIPA   1382730                 4
4                              AYACUCHO    616176                16
5                             CAJAMARCA   1341012                 5
6   Provincia Constitucional del CALLAO    994494                11
7                                 CUSCO   1205527                 7
8                          HUANCAVELICA    347639                20
9                               HUÁNUCO    721047                15
10                                  ICA    850765                13
11                                JUNÍN   1246038                 6
12                          LA LIBERTAD   1778080                 3
13                           LAMBAYEQUE   1197260                 8
14                                 LIMA   9485405                 1
15                               LORETO    883510                12
16                        MADRE DE DIOS    141070                25
17                             MOQUEGUA    174863                24
18                                PASCO    254065                22
19                                PIURA   1856809                 2
20                                 PUNO   1172697                 9
21                           SAN MARTÍN    813381                14
22                                TACNA    329332                21
23                               TUMBES    224863                23
24                              UCAYALI    496459                17

In [384]:
ranking_poblacion = ranking_poblacion.sort_values(by='Ranking población')
ranking_poblacion

                           DEPARTAMENTO Población Ranking población
14                                 LIMA   9485405                 1
19                                PIURA   1856809                 2
12                          LA LIBERTAD   1778080                 3
3                              AREQUIPA   1382730                 4
5                             CAJAMARCA   1341012                 5
11                                JUNÍN   1246038                 6
7                                 CUSCO   1205527                 7
13                           LAMBAYEQUE   1197260                 8
20                                 PUNO   1172697                 9
1                                ANCASH   1083519                10
6   Provincia Constitucional del CALLAO    994494                11
15                               LORETO    883510                12
10                                  ICA    850765                13
21                           SAN MARTÍN    813381                14
9                               HUÁNUCO    721047                15
4                              AYACUCHO    616176                16
24                              UCAYALI    496459                17
2                              APURÍMAC    405759                18
0                              AMAZONAS    379384                19
8                          HUANCAVELICA    347639                20
22                                TACNA    329332                21
18                                PASCO    254065                22
23                               TUMBES    224863                23
17                             MOQUEGUA    174863                24
16                        MADRE DE DIOS    141070                25

In [385]:
#Lista con ranking (Índice de Desarrollo Humano-departamento-ranking)
ranking_IDH = IDH_depatamentos[['DEPARTAMENTO', 'Índice de Desarrollo Humano', 'Ranking IDH']]
ranking_IDH

,DEPARTAMENTO,Índice de Desarrollo Humano,Ranking IDH
0,AMAZONAS,0.417452,21
1,ANCASH,0.488391,12
2,APURÍMAC,0.416742,22
3,AREQUIPA,0.634479,4
4,AYACUCHO,0.409602,23
5,CAJAMARCA,0.40106,24
6,Provincia Constitucional del CALLAO,0.666302,2
7,CUSCO,0.470121,15
8,HUANCAVELICA,0.335663,25
9,HUÁNUCO,0.428468,19
10,ICA,0.612103,5
11,JUNÍN,0.495384,11
12,LA LIBERTAD,0.538779,10
13,LAMBAYEQUE,0.53949,9
14,LIMA,0.715651,1
15,LORETO,0.454914,18
16,MADRE DE DIOS,0.56188,7
17,MOQUEGUA,0.638726,3
18,PASCO,0.460667,17
19,PIURA,0.479728,13
20,PUNO,0.427841,20
21,SAN MARTÍN,0.467982,16
22,TACNA,0.606991,6
23,TUMBES,0.559666,8
24,UCAYALI,0.470985,14

In [386]:
ranking_IDH = ranking_IDH.sort_values(by='Ranking IDH',ascending=False)
ranking_IDH

,DEPARTAMENTO,Índice de Desarrollo Humano,Ranking IDH
8,HUANCAVELICA,0.335663,25
5,CAJAMARCA,0.40106,24
4,AYACUCHO,0.409602,23
2,APURÍMAC,0.416742,22
0,AMAZONAS,0.417452,21
20,PUNO,0.427841,20
9,HUÁNUCO,0.428468,19
15,LORETO,0.454914,18
18,PASCO,0.460667,17
21,SAN MARTÍN,0.467982,16
7,CUSCO,0.470121,15
24,UCAYALI,0.470985,14
19,PIURA,0.479728,13
1,ANCASH,0.488391,12
11,JUNÍN,0.495384,11
12,LA LIBERTAD,0.538779,10
13,LAMBAYEQUE,0.53949,9
23,TUMBES,0.559666,8
16,MADRE DE DIOS,0.56188,7
22,TACNA,0.606991,6
10,ICA,0.612103,5
3,AREQUIPA,0.634479,4
17,MOQUEGUA,0.638726,3
6,Provincia Constitucional del CALLAO,0.666302,2
14,LIMA,0.715651,1

In [387]:
#Lista con ranking (Esperanza de vida al nacer (años)-departamento-ranking)
ranking_esperanza_vida = IDH_depatamentos[['Ranking esperanza de vida al nacer','DEPARTAMENTO', 'Esperanza de vida al nacer (años)']]
ranking_esperanza_vida

,Ranking esperanza de vida al nacer,DEPARTAMENTO,Esperanza de vida al nacer (años)
0,15,AMAZONAS,73.306564
1,10,ANCASH,75.743889
2,19,APURÍMAC,72.634854
3,6,AREQUIPA,78.203421
4,22,AYACUCHO,71.078435
5,11,CAJAMARCA,74.746021
6,1,Provincia Constitucional del CALLAO,82.515232
7,23,CUSCO,70.740178
8,25,HUANCAVELICA,64.034012
9,17,HUÁNUCO,73.110342
10,2,ICA,81.663418
11,16,JUNÍN,73.181276
12,9,LA LIBERTAD,77.214338
13,8,LAMBAYEQUE,77.288576
14,3,LIMA,81.153518
15,21,LORETO,71.419194
16,12,MADRE DE DIOS,73.718619
17,4,MOQUEGUA,79.800886
18,20,PASCO,72.040411
19,14,PIURA,73.696331
20,24,PUNO,68.475641
21,13,SAN MARTÍN,73.718529
22,7,TACNA,77.53434
23,5,TUMBES,79.057924
24,18,UCAYALI,72.861223

In [388]:
ranking_esperanza_vida = ranking_esperanza_vida.sort_values(by='Ranking esperanza de vida al nacer',ascending=True)
ranking_esperanza_vida

,Ranking esperanza de vida al nacer,DEPARTAMENTO,Esperanza de vida al nacer (años)
6,1,Provincia Constitucional del CALLAO,82.515232
10,2,ICA,81.663418
14,3,LIMA,81.153518
17,4,MOQUEGUA,79.800886
23,5,TUMBES,79.057924
3,6,AREQUIPA,78.203421
22,7,TACNA,77.53434
13,8,LAMBAYEQUE,77.288576
12,9,LA LIBERTAD,77.214338
1,10,ANCASH,75.743889
5,11,CAJAMARCA,74.746021
16,12,MADRE DE DIOS,73.718619
21,13,SAN MARTÍN,73.718529
19,14,PIURA,73.696331
0,15,AMAZONAS,73.306564
11,16,JUNÍN,73.181276
9,17,HUÁNUCO,73.110342
24,18,UCAYALI,72.861223
2,19,APURÍMAC,72.634854
18,20,PASCO,72.040411
15,21,LORETO,71.419194
4,22,AYACUCHO,71.078435
7,23,CUSCO,70.740178
20,24,PUNO,68.475641
8,25,HUANCAVELICA,64.034012

In [389]:
#Lista con ranking (Con Educación secundaria completa % (Poblac. 18)-departamento-ranking)
ranking_secundaria_completa = IDH_depatamentos[['DEPARTAMENTO', 'Con Educación secundaria completa % (Poblac. 18)','Ranking Educación secundaria completa']]
ranking_secundaria_completa

,DEPARTAMENTO,Con Educación secundaria completa % (Poblac. 18),Ranking Educación secundaria completa
0,AMAZONAS,46.859333,24
1,ANCASH,61.110602,16
2,APURÍMAC,65.547677,13
3,AREQUIPA,77.80172,1
4,AYACUCHO,59.357975,18
5,CAJAMARCA,51.376462,23
6,Provincia Constitucional del CALLAO,73.497518,6
7,CUSCO,66.690447,11
8,HUANCAVELICA,56.184207,19
9,HUÁNUCO,53.614801,20
10,ICA,73.527836,5
11,JUNÍN,65.8842,12
12,LA LIBERTAD,60.848472,17
13,LAMBAYEQUE,67.090434,9
14,LIMA,75.707688,2
15,LORETO,45.044803,25
16,MADRE DE DIOS,63.758325,14
17,MOQUEGUA,74.491285,4
18,PASCO,68.253589,8
19,PIURA,61.930024,15
20,PUNO,72.150998,7
21,SAN MARTÍN,52.462043,21
22,TACNA,74.913182,3
23,TUMBES,66.70287,10
24,UCAYALI,51.943499,22

In [390]:
ranking_secundaria_completa = ranking_secundaria_completa.sort_values(by='Ranking Educación secundaria completa',ascending=False)
ranking_secundaria_completa

,DEPARTAMENTO,Con Educación secundaria completa % (Poblac. 18),Ranking Educación secundaria completa
15,LORETO,45.044803,25
0,AMAZONAS,46.859333,24
5,CAJAMARCA,51.376462,23
24,UCAYALI,51.943499,22
21,SAN MARTÍN,52.462043,21
9,HUÁNUCO,53.614801,20
8,HUANCAVELICA,56.184207,19
4,AYACUCHO,59.357975,18
12,LA LIBERTAD,60.848472,17
1,ANCASH,61.110602,16
19,PIURA,61.930024,15
16,MADRE DE DIOS,63.758325,14
2,APURÍMAC,65.547677,13
11,JUNÍN,65.8842,12
7,CUSCO,66.690447,11
23,TUMBES,66.70287,10
13,LAMBAYEQUE,67.090434,9
18,PASCO,68.253589,8
20,PUNO,72.150998,7
6,Provincia Constitucional del CALLAO,73.497518,6
10,ICA,73.527836,5
17,MOQUEGUA,74.491285,4
22,TACNA,74.913182,3
14,LIMA,75.707688,2
3,AREQUIPA,77.80172,1

In [391]:
#Lista con ranking (Años de educación (Poblac. 25 y más)-departamento-ranking)
ranking_años_educacion = IDH_depatamentos[['Ranking años de educación','DEPARTAMENTO', 'Años de educación (Poblac. 25 y más)']]
ranking_años_educacion

,Ranking años de educación,DEPARTAMENTO,Años de educación (Poblac. 25 y más)
0,23,AMAZONAS,6.050521
1,15,ANCASH,7.633381
2,21,APURÍMAC,6.610242
3,2,AREQUIPA,10.097563
4,19,AYACUCHO,6.905559
5,25,CAJAMARCA,5.607542
6,3,Provincia Constitucional del CALLAO,10.062423
7,14,CUSCO,7.798155
8,24,HUANCAVELICA,5.735151
9,22,HUÁNUCO,6.572781
10,5,ICA,9.905355
11,10,JUNÍN,8.381481
12,13,LA LIBERTAD,8.033712
13,9,LAMBAYEQUE,8.445149
14,1,LIMA,10.35686
15,17,LORETO,7.560003
16,7,MADRE DE DIOS,8.726031
17,4,MOQUEGUA,9.921653
18,11,PASCO,8.141167
19,16,PIURA,7.577943
20,18,PUNO,7.447559
21,20,SAN MARTÍN,6.644659
22,6,TACNA,9.810744
23,8,TUMBES,8.666748
24,12,UCAYALI,8.052112

In [392]:
ranking_años_educacion = ranking_años_educacion.sort_values(by='Ranking años de educación',ascending=True)
ranking_años_educacion

,Ranking años de educación,DEPARTAMENTO,Años de educación (Poblac. 25 y más)
14,1,LIMA,10.35686
3,2,AREQUIPA,10.097563
6,3,Provincia Constitucional del CALLAO,10.062423
17,4,MOQUEGUA,9.921653
10,5,ICA,9.905355
22,6,TACNA,9.810744
16,7,MADRE DE DIOS,8.726031
23,8,TUMBES,8.666748
13,9,LAMBAYEQUE,8.445149
11,10,JUNÍN,8.381481
18,11,PASCO,8.141167
24,12,UCAYALI,8.052112
12,13,LA LIBERTAD,8.033712
7,14,CUSCO,7.798155
1,15,ANCASH,7.633381
19,16,PIURA,7.577943
15,17,LORETO,7.560003
20,18,PUNO,7.447559
4,19,AYACUCHO,6.905559
21,20,SAN MARTÍN,6.644659
2,21,APURÍMAC,6.610242
9,22,HUÁNUCO,6.572781
0,23,AMAZONAS,6.050521
8,24,HUANCAVELICA,5.735151
5,25,CAJAMARCA,5.607542

In [393]:
#Lista con ranking (Ingreso familiar per cápita-departamento-ranking)
ranking_ingreso = IDH_depatamentos[['Ranking ingreso familiar','Ingreso familiar per cápita', 'DEPARTAMENTO']]
ranking_ingreso

,Ranking ingreso familiar,Ingreso familiar per cápita,DEPARTAMENTO
0,18,629.7113,AMAZONAS
1,13,712.6623,ANCASH
2,24,511.8983,APURÍMAC
3,4,1088.0636,AREQUIPA
4,23,512.4642,AYACUCHO
5,21,551.7471,CAJAMARCA
6,2,1198.1964,Provincia Constitucional del CALLAO
7,17,667.9998,CUSCO
8,25,398.1561,HUANCAVELICA
9,19,604.6419,HUÁNUCO
10,7,958.9974,ICA
11,14,710.3179,JUNÍN
12,8,892.1488,LA LIBERTAD
13,10,827.6347,LAMBAYEQUE
14,1,1464.2608,LIMA
15,12,736.7302,LORETO
16,6,1000.6915,MADRE DE DIOS
17,3,1112.4407,MOQUEGUA
18,20,591.7423,PASCO
19,16,702.9804,PIURA
20,22,532.3485,PUNO
21,11,770.4451,SAN MARTÍN
22,5,1003.4997,TACNA
23,9,879.4833,TUMBES
24,15,710.1024,UCAYALI

In [394]:
ranking_ingreso = ranking_ingreso.sort_values(by='Ranking ingreso familiar',ascending=True)
ranking_ingreso

,Ranking ingreso familiar,Ingreso familiar per cápita,DEPARTAMENTO
14,1,1464.2608,LIMA
6,2,1198.1964,Provincia Constitucional del CALLAO
17,3,1112.4407,MOQUEGUA
3,4,1088.0636,AREQUIPA
22,5,1003.4997,TACNA
16,6,1000.6915,MADRE DE DIOS
10,7,958.9974,ICA
12,8,892.1488,LA LIBERTAD
23,9,879.4833,TUMBES
13,10,827.6347,LAMBAYEQUE
21,11,770.4451,SAN MARTÍN
15,12,736.7302,LORETO
1,13,712.6623,ANCASH
11,14,710.3179,JUNÍN
24,15,710.1024,UCAYALI
19,16,702.9804,PIURA
7,17,667.9998,CUSCO
0,18,629.7113,AMAZONAS
9,19,604.6419,HUÁNUCO
18,20,591.7423,PASCO
5,21,551.7471,CAJAMARCA
20,22,532.3485,PUNO
4,23,512.4642,AYACUCHO
2,24,511.8983,APURÍMAC
8,25,398.1561,HUANCAVELICA

# **Funciones ⭐**

In [395]:
#función con el subconjunto "ranking_años_educacion"
def primeros_10_puestos_con_años_educacion (data,columna,n=10):
  año_educa_ordenado = ranking_años_educacion.sort_values(by=columna,ascending=True)
  primeros_puestos = año_educa_ordenado.head(n)
  print(primeros_puestos)

In [396]:
primeros_10_puestos_con_años_educacion(ranking_años_educacion,'Ranking años de educación',10)

   Ranking años de educación                         DEPARTAMENTO  \
14                         1                                 LIMA
3                          2                             AREQUIPA
6                          3  Provincia Constitucional del CALLAO
17                         4                             MOQUEGUA
10                         5                                  ICA
22                         6                                TACNA
16                         7                        MADRE DE DIOS
23                         8                               TUMBES
13                         9                           LAMBAYEQUE
11                        10                                JUNÍN

   Años de educación (Poblac. 25 y más)
14                             10.35686
3                             10.097563
6                             10.062423
17                             9.921653
10                             9.905355
22                             9.810744
16                             8.726031
23                             8.666748
13                             8.445149
11                             8.381481

In [397]:
def ultimos_10_puestos_secundaria_completa(data,columna,n=3):
  secu_completa_ordenada_inversa = ranking_secundaria_completa.sort_values(by='Ranking Educación secundaria completa',ascending=False)
  ultimos_puestos = secu_completa_ordenada_inversa.head(3)
  print(ultimos_puestos)

In [398]:
ultimos_10_puestos_secundaria_completa(ranking_secundaria_completa,'Ranking Educación secundaria completa',3)

   DEPARTAMENTO Con Educación secundaria completa % (Poblac. 18)  \
15       LORETO                                        45.044803
0      AMAZONAS                                        46.859333
5     CAJAMARCA                                        51.376462

   Ranking Educación secundaria completa
15                                    25
0                                     24
5                                     23

# **Gráficos** ⭐ :

In [399]:
import altair as alt

In [400]:
alt.Chart(ranking_ingreso).mark_point().encode(
    x=alt.X('DEPARTAMENTO'),
    y=alt.Y('Ingreso familiar per cápita')
)

alt.Chart(...)

In [413]:
alt.Chart(ranking_años_educacion).mark_bar().encode(
    y=alt.Y('DEPARTAMENTO'),
    x=alt.X('Ranking años de educación')
)

alt.Chart(...)

In [402]:
ranking_años_educacion.columns

Index(['Ranking años de educación', 'DEPARTAMENTO',
       'Años de educación (Poblac. 25 y más)'],
      dtype='object')

In [409]:
alt.Chart(ranking_secundaria_completa).mark_line().encode(
    x=alt.X('DEPARTAMENTO'),
    y=alt.Y('Ranking Educación secundaria completa')
)

alt.Chart(...)

In [404]:
ranking_secundaria_completa.columns

Index(['DEPARTAMENTO', 'Con Educación secundaria completa % (Poblac. 18)',
       'Ranking Educación secundaria completa'],
      dtype='object')